### ISSUE TITLE
Incompatible with hullmods from other mods

### ISSUE THREAD

**Issue by Lawrence-Krystal** [lyravega/lyr_ehm#2]
As title says it crashes with any modded hullmods...
![image](https://github.com/lyravega/lyr_ehm/assets/125222547/fae76d20-09f8-40d6-af9b-59204c845075)
![image](https://github.com/lyravega/lyr_ehm/assets/125222547/566d91ca-8afa-426d-8e22-a3ef6c8ea8ca)

**Comment by lyravega** [comment]
Fixed in 0.7.1
